import {
  Wallet,
  ArrowLeftRight,
  TrendingUp,
  Landmark,
  Globe,
  CreditCard,
  FlaskConical,
  Crown,
} from "lucide-react";

// Mission definitions. Progress comes from lifetime stats tracked in
// TxContext; rewards are credited to the demo portfolio on claim.
export const quests = [
  {
    id: "connect",
    title: "Connect a wallet",
    description: "Link MetaMask to Nex Exchange",
    icon: Wallet,
    statKey: "connect",
    target: 1,
    reward: { amount: 0.25, symbol: "USDT" },
  },
  {
    id: "first-swap",
    title: "First swap",
    description: "Complete your first token swap",
    icon: ArrowLeftRight,
    statKey: "swaps",
    target: 1,
    reward: { amount: 0.5, symbol: "USDT" },
  },
  {
    id: "first-bridge",
    title: "Bridge pioneer",
    description: "Move assets across chains for the first time",
    icon: Landmark,
    statKey: "bridges",
    target: 1,
    reward: { amount: 1, symbol: "USDT" },
  },
  {
    id: "first-buy",
    title: "Top up",
    description: "Buy crypto with fiat in the Buy tab",
    icon: CreditCard,
    statKey: "buys",
    target: 1,
    reward: { amount: 0.5, symbol: "USDT" },
  },
  {
    id: "swap-5",
    title: "Volume trader",
    description: "Complete 5 swaps in total",
    icon: TrendingUp,
    statKey: "swaps",
    target: 5,
    reward: { amount: 2.5, symbol: "USDC" },
  },
  {
    id: "bridge-3",
    title: "Multichain explorer",
    description: "Complete 3 bridge transfers",
    icon: Globe,
    statKey: "bridges",
    target: 3,
    reward: { amount: 3, symbol: "USDC" },
  },
  {
    id: "testnet-1",
    title: "Go on-chain",
    description: "Complete a real transaction in Testnet mode",
    icon: FlaskConical,
    statKey: "testnetTxs",
    target: 1,
    reward: { amount: 5, symbol: "USDT" },
  },
  {
    id: "all",
    title: "Nex legend",
    description: "Claim every other mission",
    icon: Crown,
    statKey: "claimedOthers",
    target: 7,
    reward: { amount: 10, symbol: "USDC" },
  },
];
